apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  type: NodePort  # You can change this to LoadBalancer if using a cloud provider
  selector:
    app: my-node-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001  # Optional, specify a port if you want
